### ISSUE TITLE
fantastic work

### ISSUE THREAD

**Issue by mikermcneil** [jch/saml#5]
@jch just wanted to say thank you for writing this out in such clear language.  I particularly appreciated your analogy to OAuth:

> SAML lets you manage user identities and authorizations across multiple apps. It's similar to how we use our Google identity to login to YouTube, or our Facebook identity for.... errr everything else.
>
> Large companies love single sign-on. Instead of using OAuth, they use SAML. And instead of Farmville, it's Enterprise Software™. Po-tay-toes, Po-tah-toes.

I think those few sentences are incredibly important, since they clear up what is a major point of confusion for a lot of folks (myself included).

**Comment by jch** [comment]
Thanks @mikermcneil, appreciate the kind words ;)
